# Generated by Django 5.0.1 on 2024-01-10 21:00

import django.db.models.deletion
import django.utils.timezone
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(choices=[('Cool White', 'Cool White'), ('Warm White', 'Warm White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Pink', 'Pink'), ('Hot Pink', 'Hot Pink'), ('Purple', 'Purple'), ('Blue', 'Blue'), ('Ice Blue', 'Ice Blue'), ('Green', 'Green')], max_length=255)),
                ('design_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('cut_type', models.CharField(choices=[('Cut to Shape', 'Cut to Shape'), ('Square/Rectangle', 'Square/Rectangle'), ('Cut to Letter', 'Cut to Letter'), ('Circular/Round', 'Circular/Round')], max_length=255)),
                ('is_business', models.BooleanField(blank=True, default=False, null=True)),
                ('order_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('shipping_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('New Order', 'New Order'), ('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Needs Design', 'Needs Design'), ('Design Ready', 'Design Ready'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Awaits Pickup', 'Awaits Pickup'), ('Delivered', 'Delivered')], max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('company_notes', models.TextField(blank=True)),
                ('acrylic_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('silicone_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('silicone_amount_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('led_light_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('led_light_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('power_supply_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mounting_accessories_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=orders.models.order_image_path)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
