# Generated by Django 5.0.1 on 2024-01-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderimage_is_mockup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warranty_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
