# Generated by Django 5.0.1 on 2024-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_warranty_duration_order_warranty_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
