# Generated by Django 5.0.1 on 2024-01-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_warranty_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
