# Generated by Django 5.0.1 on 2024-01-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('new_order', 'New Order'), ('in_progress', 'In Progress'), ('needs_design', 'Needs Design'), ('design_ready', 'Design Ready'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('awaits_pickup', 'Awaits Pickup'), ('delivered', 'Delivered'), ('complete', 'Complete')], max_length=20, null=True),
        ),
    ]
